#include<iostream.h>
#include<conio.h>

void main()
  {
     int roll,age;
     char add[100],name[100];
     clrscr();


     cout<<"Enter your roll no=";
     cin>>roll;

     cout<<"Enter your name=";
     cin>>name;

     cout<<"Enter your age=";
     cin>>age;

     cout<<"Enter your address";
     cin>>add;


     cout<<"Name="<<name<<endl<<"Roll No="<<roll<<endl<<"Age="<<age<<endl<<"Address="<<add;


     getch();
     }